name: Deploy PBIP to Power BI

on:
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

jobs:
  deploy:
    runs-on: windows-latest  # Usa un runner de Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Dependencies
        shell: pwsh
        run: |
          $path = "${{ github.workspace }}"
          $workingFolder = "$path\.ado"

          New-Item -ItemType Directory -Path "$workingFolder\modules" -ErrorAction SilentlyContinue | Out-Null

          Write-Host "Downloading FabricPS-PBIP module"
          @(
              "https://raw.githubusercontent.com/microsoft/Analysis-Services/master/pbidevmode/fabricps-pbip/FabricPS-PBIP.psm1",
              "https://raw.githubusercontent.com/microsoft/Analysis-Services/master/pbidevmode/fabricps-pbip/FabricPS-PBIP.psd1") |% {    
                  Invoke-WebRequest -Uri $_ -OutFile "$workingFolder\modules\$(Split-Path $_ -Leaf)"
              }

          Write-Host "Installing Az.Accounts module"
          if(-not (Get-Module Az.Accounts -ListAvailable)){
              Install-Module Az.Accounts -Scope CurrentUser -Force
          }

      - name: Deploy PBIP to Power BI
        shell: pwsh
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
          ADMIN_PRINCIPAL_ID: ${{ secrets.ADMIN_PRINCIPAL_ID }}
        run: |
          $path = "${{ github.workspace }}"
          $appId = "${{ env.APP_ID }}"
          $appSecret = "${{ env.APP_SECRET }}"
          $tenantId = "${{ env.TENANT_ID }}"                                        
          $workspaceId = "${{ env.WORKSPACE_ID }}"
          $adminPrincipalId = "${{ env.ADMIN_PRINCIPAL_ID }}"

          # Rutas de los archivos PBIP (ajusta los nombres según tu estructura)
          $pbipSemanticModelPath = "$path\Caso_Tutorial.SemanticModel"
          $pbipReportPath = "$path\Caso_Tutorial.Report"

          $workingFolder = "$path\.ado"
          Import-Module "$workingFolder\modules\FabricPS-PBIP" -Force

          Write-Host "Authenticating with Service Principal"
          Set-FabricAuthToken -servicePrincipalId $appId -servicePrincipalSecret $appSecret -tenantId $tenantId -reset

          $workspacePermissions = @{
              "principal" = @{
                  "id" = "$adminPrincipalId"
                  "type" = "user"
              }
              "role"= "Admin"
          }

          Write-Host "Ensuring Fabric Workspace & permissions"
          Set-FabricWorkspacePermissions $workspaceId $workspacePermissions

          Write-Host "Publishing Semantic Model"
          $semanticModelImport = Import-FabricItem -workspaceId $workspaceId -path $pbipSemanticModelPath

          Write-Host "Publishing Report"
          $reportImport = Import-FabricItem -workspaceId $workspaceId -path $pbipReportPath -itemProperties @{"semanticModelId"=$semanticModelImport.Id}
